import { i18n } from '../i18n';

/**
 * MUIdle's own strings. Kept out of the game's catalogue (`i18n/recipes.ts`)
 * on purpose: a key there must be translated into every shipped language,
 * these are English and Portuguese only and fall back to English.
 */
const EN = {
  hunt: 'HUNT',
  manual: 'MANUAL',
  huntHint: 'Auto hunting - keeps going on the server when you leave',
  manualHint: 'You control the character',
  safeZone: 'Leave the safe zone to start HUNT',
  idleSettings: 'Idle Settings',
  helperSettings: 'Skills, potions & loot filters…',
  autoTravel: 'Auto travel (walk to hunting grounds, merchant trips)',
  performance: 'Performance',
  'perf.full': 'Full',
  'perf.reduced': 'Reduced',
  'perf.minimum': 'Minimum',
  'perf.auto': 'Automatic (by frame rate)',
  perfAutoNow: 'Automatic is on {level} now',
  huntMap: 'Hunting map',
  'huntMap.auto': 'Automatic (best map for the level)',
  'huntMap.manual': 'Manual (stay on the current map)',
  'mapReason.level': 'needs level {level}',
  'mapReason.zen': 'warp costs {zen} zen',
  'mapReason.noWarp': 'no warp to it',
  'mapReason.requirement': 'special entry requirement',
  pinnedUnavailable: 'Hunting elsewhere - the chosen map: {reason}',
  'activity.idle': 'Idle',
  'activity.hunting': 'Hunting in {map}',
  'activity.travelling': 'Walking to a hunting ground in {map}',
  'activity.warping': 'Travelling to {map}',
  'activity.shopping': 'On a shopping trip',
  'activity.buff': 'Getting a buff',
  'activity.dead': 'Dead - respawning',
  'activity.event': 'In {map}',
  events: 'Events',
  eventsFirst: 'With HUNT on, join events before hunting',
  eventsHint: 'When an event opens, the server enters it for the character if it has the ticket, the level and the zen. Untick an event to keep hunting instead.',
  eventEnrolled: 'Auto-join',
  eventOpen: 'open now',
  eventFar: 'later',
  eventReady: 'ready',
  worldBosses: 'World bosses',
  dailyContracts: 'Daily contracts (new ones at 00:00 UTC)',
  'contract.kills': 'Defeat {target} monsters',
  'contract.mapKills': 'Defeat {target} monsters in {map}',
  'contract.huntMinutes': 'Hunt for {target} minutes',
  contractDone: 'done',
  progression: 'Server progression',
  seasonWeek: 'Season {season} · week {week}',
  resetCap: 'Reset cap this week',
  resetCapNone: 'no cap',
  capRises: '+{per} on {date}',
  yourResets: 'Your resets',
  xpBonus: 'Experience bonus',
  ranking: 'Ranking',
  'line.all': 'All classes',
  'line.wizard': 'Wizards',
  'line.knight': 'Knights',
  'line.elf': 'Elves',
  'line.gladiator': 'Gladiators',
  'line.lord': 'Lords',
  'line.summoner': 'Summoners',
  'line.fighter': 'Fighters',
  rankingRow: '{resets} resets · level {level}',
  rankingYou: 'You: #{rank}',
  rankingUnavailable: 'Ranking unavailable right now.',
  cpBreakdown: 'Combat Power {total}',
  classQuest: 'Class quest',
  questLineDone: 'Every class quest is done.',
  questActive: 'in progress',
  questReady: 'ready - hand it in',
  questAccept: 'ready to accept',
  questNext: 'from level {level}',
  questGiver: 'Accept and hand in at {name}, {map} ({x}, {y}).',
  questDrop: 'drops from monsters level {min}–{max} while the quest runs',
  questDropBoss: 'drops from {monster}',
  questItemsFirst: 'HUNT (AUTO) goes where the quest item drops',
  questsAuto: 'HUNT accepts and hands in class quests (pays the start fee)',
  questFee: 'Start fee: {zen} zen',
  'questAuto.manual': 'This quest needs you at the giver.',
  'questAuto.handIn': 'HUNT goes to {giver} to hand it in.',
  'questAuto.collecting': 'HUNT is collecting what the quest needs.',
  'questAuto.level': 'HUNT accepts it from level {level}.',
  'questAuto.zen': 'Waiting for {zen} zen to accept it.',
  'questAuto.accept': 'HUNT goes to {giver} to accept it.',
  'activity.quest': 'On a quest errand in {map}',
  'activity.paused': 'HUNT paused: not enough zen for the MU Helper ({have} of {need})',
  'note.noSafeMap': 'Dying here too often, and no safer map is open',
  'note.noFare': 'A better map needs {need} zen (travel + reserve), {have} now',
  'note.questZen': 'Next quest waits for zen: {have} of {need} (fee, travel, reserve)',
  'note.deadlyHere': 'HUNT waits: died 3 times on this map in 30 minutes - pick another map or press HUNT',
  cpBase: 'From level {level} · stats {stats} · life/mana/SD {vitals}',
  cpItems: 'Equipment',
  cpEmpty: 'empty',
  cpHintEmpty: 'Cheapest next CP: equip something in the empty slot ({slot}).',
  cpHintWeak: 'Cheapest next CP: improve {item} ({power} CP).',
  xpBonusParts: '+{total}% (catch-up +{catchUp}%, newcomer +{newcomer}%)',
  xpBonusNone: 'none',
  resetNeeds: 'Next reset needs',
  resetNeedsValue: 'level {level} · {zen} zen',
  resetAfter: 'After it: level {level}, back in town, logged out to the character list.',
  resetButton: 'Reset',
  resetConfirm: 'Reset now?',
  resetCancel: 'Not now',
  'resetReason.disabled': 'Resets are off on this server.',
  'resetReason.level': 'Reach level {level} first.',
  'resetReason.cap': 'This week\'s cap is reached; it rises on {date}.',
  'resetReason.zen': 'Not enough zen ({zen}).',
  bossesFirst: 'With HUNT on, go to a world boss of my level',
  bossAlive: 'here now: {map} ({x}, {y})',
  bossNext: 'next at {time}',
  bossReward: '{zen} zen split by damage · level {level}+',
  'eventReason.level': 'level outside every event level',
  'eventReason.ticket': 'no ticket in the bag',
  'eventReason.zen': 'not enough zen for the fee',
  'eventReason.master': 'needs a master class',
  'eventReason.equipment': 'unequip {item} to enter',
  keepHuntingAfterDeath: 'Keep hunting after death',
  autoSell: 'Auto sell junk at merchants',
  autoRepair: 'Auto repair at merchants',
  autoBuyPotions: 'Auto buy potions',
  autoBuild: 'Auto build (spend stat points by class)',
  buildPreset: 'Build',
  'build.elfDefault': 'Damage (agility)',
  'build.support': 'Support (energy)',
  'build.strength': 'Strength',
  'build.energy': 'Energy',
  'build.raven': 'Raven (command)',
  sellMaxItemLevel: 'Junk = plain weapons/armor up to +{level}',
  alwaysKept: 'Never sold: equipped, excellent, ancient, socket, wings, jewels, locked items',
  save: 'Save',
  close: 'Close',
  saved: 'Idle settings saved',
  offlineProgress: 'OFFLINE PROGRESS',
  offlineTime: 'Time offline',
  monsters: 'Monsters defeated',
  experience: 'Experience',
  levels: 'Levels gained',
  masterExperience: 'Master experience',
  zenEarned: 'Zen earned',
  zenSpent: 'Zen spent',
  itemsCollected: 'Items collected',
  itemsSold: 'Items sold',
  repairs: 'Repairs',
  potions: 'Potions used',
  deaths: 'Deaths',
  maps: 'Maps visited',
  perMap: 'Per map',
  perMinute: '{value}/min',
  endReason: 'Ended',
  'reason.returned': 'you returned',
  'reason.died': 'the character died',
  'reason.allowance': 'offline time limit reached',
  'reason.interrupted': 'server interrupted',
  'reason.zen': 'out of zen',
  ok: 'OK',
  lock: 'Lock item',
  unlock: 'Unlock item',
  lockedItems: 'Lock items (never auto-sold)',
  cp: 'CP',
} as const;

export type MUIdleTextKey = keyof typeof EN;

const PT: Partial<Record<MUIdleTextKey, string>> = {
  hunt: 'CAÇAR',
  manual: 'MANUAL',
  huntHint: 'Caça automática - continua no servidor quando você sai',
  manualHint: 'Você controla o personagem',
  safeZone: 'Saia da zona segura para iniciar a caça',
  idleSettings: 'Configurações Idle',
  helperSettings: 'Skills, poções e filtros de loot…',
  autoTravel: 'Viagem automática (ir às áreas de caça, viagens ao mercador)',
  performance: 'Desempenho',
  'perf.full': 'Completo',
  'perf.reduced': 'Reduzido',
  'perf.minimum': 'Mínimo',
  'perf.auto': 'Automático (pelo FPS)',
  perfAutoNow: 'O automático está em {level} agora',
  huntMap: 'Mapa de caça',
  'huntMap.auto': 'Automático (melhor mapa para o nível)',
  'huntMap.manual': 'Manual (ficar no mapa atual)',
  'mapReason.level': 'exige nível {level}',
  'mapReason.zen': 'o warp custa {zen} zen',
  'mapReason.noWarp': 'sem warp até ele',
  'mapReason.requirement': 'requisito especial de entrada',
  pinnedUnavailable: 'Caçando em outro lugar - o mapa escolhido: {reason}',
  'activity.idle': 'Parado',
  'activity.hunting': 'Caçando em {map}',
  'activity.travelling': 'Indo para uma área de caça em {map}',
  'activity.warping': 'Viajando para {map}',
  'activity.shopping': 'Indo ao mercador',
  'activity.buff': 'Pegando buff',
  'activity.dead': 'Morto - renascendo',
  'activity.event': 'Em {map}',
  events: 'Eventos',
  eventsFirst: 'Com CAÇAR ligado, entrar nos eventos antes de caçar',
  eventsHint: 'Quando um evento abre, o servidor entra nele pelo personagem se ele tiver o ingresso, o nível e o zen. Desmarque um evento para continuar caçando.',
  eventEnrolled: 'Entrar sozinho',
  eventOpen: 'aberto agora',
  eventFar: 'mais tarde',
  eventReady: 'pronto',
  worldBosses: 'Chefes do mundo',
  dailyContracts: 'Contratos diários (novos às 00:00 UTC)',
  'contract.kills': 'Derrote {target} monstros',
  'contract.mapKills': 'Derrote {target} monstros em {map}',
  'contract.huntMinutes': 'Cace por {target} minutos',
  contractDone: 'concluído',
  progression: 'Progresso do servidor',
  seasonWeek: 'Temporada {season} · semana {week}',
  resetCap: 'Limite de resets da semana',
  resetCapNone: 'sem limite',
  capRises: '+{per} em {date}',
  yourResets: 'Seus resets',
  xpBonus: 'Bônus de experiência',
  ranking: 'Ranking',
  'line.all': 'Todas as classes',
  'line.wizard': 'Magos',
  'line.knight': 'Cavaleiros',
  'line.elf': 'Elfas',
  'line.gladiator': 'Gladiadores',
  'line.lord': 'Lordes',
  'line.summoner': 'Invocadoras',
  'line.fighter': 'Lutadores',
  rankingRow: '{resets} resets · nível {level}',
  rankingYou: 'Você: #{rank}',
  rankingUnavailable: 'Ranking indisponível agora.',
  cpBreakdown: 'Poder de combate {total}',
  classQuest: 'Quest de classe',
  questLineDone: 'Todas as quests de classe estão feitas.',
  questActive: 'em andamento',
  questReady: 'pronta - entregue',
  questAccept: 'pronta para aceitar',
  questNext: 'a partir do nível {level}',
  questGiver: 'Aceite e entregue com {name}, {map} ({x}, {y}).',
  questDrop: 'cai de monstros nível {min}–{max} enquanto a quest estiver ativa',
  questDropBoss: 'cai de {monster}',
  questItemsFirst: 'CAÇAR (AUTO) vai onde o item da quest cai',
  questsAuto: 'CAÇAR aceita e entrega as quests de classe (paga a taxa)',
  questFee: 'Taxa para começar: {zen} zen',
  'questAuto.manual': 'Esta quest precisa de você no NPC.',
  'questAuto.handIn': 'CAÇAR vai até {giver} para entregar.',
  'questAuto.collecting': 'CAÇAR está juntando o que a quest pede.',
  'questAuto.level': 'CAÇAR aceita a partir do nível {level}.',
  'questAuto.zen': 'Esperando {zen} zen para aceitar.',
  'questAuto.accept': 'CAÇAR vai até {giver} para aceitar.',
  'activity.quest': 'Em missão de quest em {map}',
  'activity.paused': 'CAÇAR pausado: zen insuficiente para o MU Helper ({have} de {need})',
  'note.noSafeMap': 'Morrendo demais aqui, e nenhum mapa mais seguro está disponível',
  'note.noFare': 'Um mapa melhor precisa de {need} zen (viagem + reserva), tem {have}',
  'note.questZen': 'Próxima quest espera zen: {have} de {need} (taxa, viagem, reserva)',
  'note.deadlyHere': 'CAÇAR aguardando: 3 mortes neste mapa em 30 minutos - escolha outro mapa ou aperte CAÇAR',
  cpBase: 'Do nível {level} · atributos {stats} · vida/mana/SD {vitals}',
  cpItems: 'Equipamento',
  cpEmpty: 'vazio',
  cpHintEmpty: 'CP mais barato: equipe algo no espaço vazio ({slot}).',
  cpHintWeak: 'CP mais barato: melhore {item} ({power} CP).',
  xpBonusParts: '+{total}% (atraso +{catchUp}%, novato +{newcomer}%)',
  xpBonusNone: 'nenhum',
  resetNeeds: 'O próximo reset exige',
  resetNeedsValue: 'nível {level} · {zen} zen',
  resetAfter: 'Depois: nível {level}, de volta à cidade, sai para a lista de personagens.',
  resetButton: 'Resetar',
  resetConfirm: 'Resetar agora?',
  resetCancel: 'Agora não',
  'resetReason.disabled': 'Os resets estão desligados neste servidor.',
  'resetReason.level': 'Chegue ao nível {level} primeiro.',
  'resetReason.cap': 'O limite da semana foi atingido; ele sobe em {date}.',
  'resetReason.zen': 'Zen insuficiente ({zen}).',
  bossesFirst: 'Com CAÇAR ligado, ir ao chefe do mundo do meu nível',
  bossAlive: 'agora: {map} ({x}, {y})',
  bossNext: 'próximo às {time}',
  bossReward: '{zen} zen divididos pelo dano · nível {level}+',
  'eventReason.level': 'nível fora dos níveis do evento',
  'eventReason.ticket': 'sem ingresso na bolsa',
  'eventReason.zen': 'zen insuficiente para a entrada',
  'eventReason.master': 'exige classe master',
  'eventReason.equipment': 'tire {item} para entrar',
  keepHuntingAfterDeath: 'Continuar caçando após morrer',
  autoSell: 'Vender lixo automaticamente',
  autoRepair: 'Reparar automaticamente no NPC',
  autoBuyPotions: 'Comprar poções automaticamente',
  autoBuild: 'Distribuir pontos automaticamente (por classe)',
  buildPreset: 'Build',
  'build.elfDefault': 'Dano (agilidade)',
  'build.support': 'Suporte (energia)',
  'build.strength': 'Força',
  'build.energy': 'Energia',
  'build.raven': 'Corvo (comando)',
  sellMaxItemLevel: 'Lixo = armas/armaduras comuns até +{level}',
  alwaysKept: 'Nunca vendidos: equipados, excellent, ancient, socket, asas, joias, itens travados',
  save: 'Salvar',
  close: 'Fechar',
  saved: 'Configurações idle salvas',
  offlineProgress: 'PROGRESSO OFFLINE',
  offlineTime: 'Tempo offline',
  monsters: 'Monstros derrotados',
  experience: 'Experiência',
  levels: 'Níveis obtidos',
  masterExperience: 'Master XP',
  zenEarned: 'Zen ganho',
  zenSpent: 'Zen gasto',
  itemsCollected: 'Itens coletados',
  itemsSold: 'Itens vendidos',
  repairs: 'Reparos',
  potions: 'Poções usadas',
  deaths: 'Mortes',
  maps: 'Mapas visitados',
  perMap: 'Por mapa',
  perMinute: '{value}/min',
  endReason: 'Encerrado',
  'reason.returned': 'você voltou',
  'reason.died': 'o personagem morreu',
  'reason.allowance': 'limite de tempo offline',
  'reason.interrupted': 'servidor interrompido',
  'reason.zen': 'sem zen',
  ok: 'OK',
  lock: 'Travar item',
  unlock: 'Destravar item',
  lockedItems: 'Travar itens (nunca vendidos automaticamente)',
};

export function mt(key: MUIdleTextKey, params?: Record<string, string | number>): string {
  const table = i18n.language === 'pt' ? PT : EN;
  let text: string = table[key] ?? EN[key];
  if (params) {
    for (const [name, value] of Object.entries(params)) {
      text = text.replace(`{${name}}`, String(value));
    }
  }
  return text;
}
