import type { Item } from '../ecs/world';
import { ITEM_ICON_MANIFEST } from './itemIconManifest';
import { itemLevelLook } from './itemLevelLook';

/**
 * The pre-rendered item icon pack (`public/items/item_<group>_<num>_<tint>[_e|_a].png`)
 * and a warm-up for it.
 *
 * Why the warm-up: an `<img>` is a *low*-priority request that Chrome parks
 * behind every high-priority `fetch()` / XHR in flight, and the world streams
 * models and textures through exactly those while the player walks. A shop
 * opened in a busy town watched its 30–100 icons trickle in six at a time
 * (HTTP/1.1 per-host limit), each batch waiting on a frame, for 20 s. The
 * warm-up fires the requests the moment the stock / inventory packet lands -
 * before React mounts a single square - at high priority, and keeps the
 * `Image` objects so the memory cache never has to revalidate them (vite's
 * `public/` answers with `Cache-Control: no-cache`).
 *
 * Which files exist comes from `itemIconManifest.ts`, generated by
 * `tools/itemIconManifest.ts` from the folder: the pack is uneven (wings and
 * most later-season items only have the `_0` tint, some groups have no
 * excellent variant, 46 `items.json` rows have no file at all), and without
 * the manifest every gap was up to three 404s per square.
 */

/** Tints the pack was rendered at: +0, +3, +5, … +15 (manifest bit order). */
export const ITEM_ICON_TINTS: readonly number[] = [0, 3, 5, 7, 9, 11, 13, 15];

export function itemIconTint(lvl: number): number {
  if (lvl < 3) return 0;
  if (lvl < 5) return 3;
  if (lvl < 7) return 5;
  if (lvl < 9) return 7;
  if (lvl < 11) return 9;
  if (lvl < 13) return 11;
  if (lvl < 15) return 13;
  return 15;
}

type Variant = '' | '_e' | '_a';

const VARIANT_BIT: Readonly<Record<Variant, number>> = {
  '': 0,
  _e: ITEM_ICON_TINTS.length,
  _a: ITEM_ICON_TINTS.length * 2,
};

/**
 * Pack pictures replaced after release, by file: a new address, since the old one is held for a day
 * by the HTTP cache (`max-age`) and for good by the download screen's worker cache (`sw.js`).
 */
const REVISED: Readonly<Record<string, number>> = {
  // MUIdle (D29): the Jewel of Life without the original's orange colour pass.
  item_14_16_0: 2,
};

function packUrl(group: number, num: number, tint: number, variant: Variant): string {
  const file = `item_${group}_${num}_${tint}${variant}`;
  const revision = REVISED[file];
  return `/items/${file}.png${revision ? `?r=${revision}` : ''}`;
}

/** Whether `public/items` holds this exact file (per the generated manifest). */
export function hasItemIconFile(
  group: number,
  num: number,
  tint: number,
  variant: Variant
): boolean {
  const mask = ITEM_ICON_MANIFEST[`${group}_${num}`];
  if (mask === undefined) return false;
  const tintIndex = ITEM_ICON_TINTS.indexOf(tint);
  if (tintIndex < 0) return false;
  return (mask & (1 << (tintIndex + VARIANT_BIT[variant]))) !== 0;
}

/** URL of the file the item asks for, whether or not it exists. */
export function itemIconPackUrl({ group, num, lvl, isExcellent }: Item): string {
  const look = itemLevelLook(group, num, lvl);
  if (look) return `/items/${look.icon}.png`;
  return packUrl(group, num, itemIconTint(lvl ?? 0), isExcellent ? '_e' : '');
}

/**
 * The files to try for this item, best first, restricted to the ones that
 * exist: the exact tint and variant, then the tint dropped, then the
 * variant dropped, then both. Empty when the item has no icon at all - the
 * caller shows the missing-icon square straight away instead of 404ing.
 */
export function itemIconPackChain(item: Item): string[] {
  const { group, num } = item;
  const look = itemLevelLook(group, num, item.lvl);
  const tint = itemIconTint(item.lvl ?? 0);
  const variant: Variant = item.isExcellent ? '_e' : item.isAncient ? '_a' : '';

  const candidates: [number, Variant][] = [[tint, variant]];
  if (tint !== 0) candidates.push([0, variant]);
  if (variant !== '') {
    candidates.push([tint, '']);
    if (tint !== 0) candidates.push([0, '']);
  }

  const urls: string[] = look ? [`/items/${look.icon}.png`] : [];
  for (const [t, v] of candidates) {
    if (hasItemIconFile(group, num, t, v)) urls.push(packUrl(group, num, t, v));
  }
  return urls;
}

/** The first file of the chain: what the icon will show, or `null` for none. */
export function itemIconUrl(item: Item): string | null {
  return itemIconPackChain(item)[0] ?? null;
}

/**
 * Identity of an item's icon - every field the file name depends on. Used
 * as the React key / effect dependency so a durability tick on the same
 * item does not restart its load.
 */
export function itemIconKey(item: Item): string {
  const look = itemLevelLook(item.group, item.num, item.lvl);
  if (look) return look.icon;
  return `${item.group}_${item.num}_${itemIconTint(item.lvl ?? 0)}${
    item.isExcellent ? '_e' : item.isAncient ? '_a' : ''
  }`;
}

/**
 * Pinned so the browser's memory cache keeps the decoded file. Bounded: a
 * long session through vault, shops and trades would otherwise pin every
 * icon ever seen (8 k files, 65 MB on disk). Insertion-ordered `Map` as an
 * LRU - a hit is re-inserted at the end, the oldest entry is dropped past
 * the cap.
 */
const WARM_CAP = 512;
const warmed = new Map<string, HTMLImageElement>();

/** Start loading the icons of these items now, ahead of the grid that shows them. */
export function prefetchItemIcons(
  items: Iterable<Item | null | undefined>
): void {
  if (typeof Image === 'undefined') return;

  for (const item of items) {
    if (!item) continue;
    const url = itemIconUrl(item);
    if (!url) continue;

    const hit = warmed.get(url);
    if (hit) {
      warmed.delete(url);
      warmed.set(url, hit);
      continue;
    }

    const img = new Image();
    // Not in @types/react 18 / lib.dom of this TS: set as a plain property.
    (img as HTMLImageElement & { fetchPriority?: string }).fetchPriority = 'high';
    img.decoding = 'async';
    img.src = url;
    warmed.set(url, img);

    if (warmed.size > WARM_CAP) {
      const oldest = warmed.keys().next().value;
      if (oldest !== undefined) warmed.delete(oldest);
    }
  }
}
